@startuml

package "Backend" {

    package "End Point" {
        [Application.Controller] - [DTO]
    }

    package "Business Logic" {
        [Application.Service] - [Application.Model]
    }

    package "Data Access Object" {
        [DAO] -down- [Repository]
        [Repository] -right- [Entity] : use
    }

    [Application.Controller] -down- [Application.Service]
    [Application.Service] -down- [DAO]

}

database "MySQL" {
JDBC -left- [Sample Database]
}


HTTP -down- [Application.Controller]
[Repository] -down- JDBC


@enduml